USERNAME_AUTH = 'auth'
ANOTHER_AUTHOR = 'another_author'
GROUP_TITLE_MAIN = 'Тестовая группа'
GROUP_TITLE_TEST = 'Тестовая группа 2'
GROUP_SLUG_MAIN = 'test-slug'
GROUP_SLUG_TEST = 'test-slug_2'
GROUP_DESCRIPTION_MAIN = 'Тестовое описание'
GROUP_DESCRIPTION_TEST = 'Тестовое описание 2'
POST_TEXT_MAIN = 'Тестовый пост базовый'
POST_TEXT_TEST = 'Тестовый пост'
EDIT_TEXT_POST = 'Отредактированный текст поста'
PAGE_OF_PAGINATOR = 'page_obj'
NAME_IMAGE_GIF = 'image/gif'
COMMENT_TEXT = 'Тестовый текст комментария'

TEMPLATE_INDEX = 'posts/index.html'
TEMPLATE_GROUP_LIST = 'posts/group_list.html'
TEMPLATE_PROFILE = 'posts/profile.html'
TEMPLATE_POST_DETAIL = 'posts/post_detail.html'
TEMPLATE_POST_CREATE = 'posts/create_post.html'
TEMPLATE_POST_EDIT = 'posts/create_post.html'
TEMPLATE_404_ERROR = 'core/404.html'

URL_INDEX_BASE = '/'
URL_POST_CREATE_BASE = '/create/'
URL_INDEX = 'posts:index'
URL_PROFILE = 'posts:profile'
URL_GROUP_LIST = 'posts:group_posts'
URL_POST_DETAIL = 'posts:post_detail'
URL_POST_CREATE = 'posts:post_create'
URL_POST_EDIT = 'posts:post_edit'
URL_UNEXISTING_PAGE = '/unexisting_page/'
URL_CREATE_COMMENT = 'posts:add_comment'
URL_FOLLOWING = 'posts:profile_follow'
URL_FOLLOW_INDEX = 'posts:follow_index'
URL_UNFOLLOW = 'posts:profile_unfollow'

FIRST_LIST_PAGINATOR = '1'
SECOND_LIST_PAGINATOR = '2'

NUMBERS_CREATE_POST = 13
PRINT_TEN_POSTS = 10
PRINT_THREE_POSTS = 3
